# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "CRISPRFinder Auto"
  end

  config.vm.box = "debian/jessie64"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.network :private_network, ip: "192.168.55.45"
  config.vm.hostname = "crisprfinderauto.local"

  config.vm.synced_folder "../..", "/vagrant", type: 'virtualbox'

  config.vm.provision "shell", path: "provision.sh"

end